### ISSUE TITLE
Consider moving this plugin to the asdf-community

### ISSUE THREAD

**Issue by smorimoto** [asdf-community/asdf-hashicorp#18]
Hi @nikolay @rubbish, thanks for creating this plugin. We recently started a community project to maintenance the asdf plugins. I hope you are interested in moving this plugin there and maintaining it with the help of many people.

**Comment by smorimoto** [comment]
@radditude Perhaps you are also interested in helping that?

**Comment by smorimoto** [comment]
Check here for an overview of the project: https://github.com/asdf-community/.github

**Comment by radditude** [comment]
I would be more than happy to help with maintenance! As a HashiCorp employee and frequent asdf user, I use this plugin quite a bit 😄

**Comment by smorimoto** [comment]
Thank you @radditude! Then let's wait for their response :)

**Comment by nikolay** [comment]
@smorimoto I no longer work at the company, so, I can't help, sorry, but thank you for the asdf-community project!

**Comment by DustinChaloupka** [comment]
I started a discussion on the community github repo as suggested.

**Comment by smorimoto** [comment]
@nikolay Ah, I didn't know that! Sorry for the disturbance!
@DustinChaloupka Cool! I just repried!

**Comment by smorimoto** [comment]
Done.
