### ISSUE TITLE
asdf on M1 macs tries and fails to download a Darwin ARM version of terraform

### ISSUE THREAD

**Issue by paul-civitas** [asdf-community/asdf-hashicorp#30]
```
Downloading terraform version 0.12.29 from https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_darwin_arm.zip
Error: terraform version 0.12.29 not found
```

Hashicorp hasn't released new silicon versions of terraform yet, but the amd64 versions work fine due to Rosetta.

asdf should download arm versions if they're available (currently not released for any stable version) and fall back on a Rosetta compatible amd64 version if there's no arm version available.

**Comment by radditude** [comment]
> currently not released for any stable version

This is actually not entirely true! [Packer](https://releases.hashicorp.com/packer/1.7.2/) and [Waypoint](https://releases.hashicorp.com/waypoint/0.3.2/) include `darwin_arm64` builds for new releases today, and the other products are coming soon.

**Comment by radditude** [comment]
Closing this now that #31 is merged! Thanks for bringing this up.
