### ISSUE TITLE
Can't install terraform versions

### ISSUE THREAD

**Issue by bdubaut** [asdf-community/asdf-hashicorp#34]
Hi,

I've been trying to install terraform using asdf, and while I am able to add the plugin, I can't seem to be able to install any of the versions:

```
❯ asdf install terraform 0.15.5
Downloading terraform version 0.15.5 from https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_darwin_arm.zip
Error: terraform version 0.15.5 not found
```

Is there something I am doing wrong?

### Current setup
**OS** MacOS Big Sur
**ASDF version** v0.8.1
**terraform plugin version** is up to date with `origin/master`

**Comment by radditude** [comment]
Are you on an M1 Mac by any chance? I see that it's trying to download the `darwin_arm` binary, which doesn't exist and would explain the `not found` error!

If you have Rosetta installed, you can tell asdf to grab the `amd64` binary instead by setting `ASDF_HASHICORP_OVERWRITE_ARCH=amd64`.

**Comment by bdubaut** [comment]
Ah yes indeed I am on the M1 Mac. Thanks!
