### ISSUE TITLE
Can't Install Terraform Version 1.0.3

### ISSUE THREAD

**Issue by rsc3600** [asdf-community/asdf-hashicorp#52]
Hello, 

I'm using asdf version v0.10.1 and trying to install terraform version 1.0.3, but I am getting the following error:

`$ asdf install terraform 1.0.3`
`Downloading terraform version 1.0.3 from https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip`
`Error: terraform version 1.0.3 not found`

I've checked hashicorp and verified that that version/path exists.

I'm using WSL 2.0 on Ubuntu-10.04.

Please let me know what I can do to resolve here.

Thanks,
Russell

**Comment by DustinChaloupka** [comment]
Hmm, I do not have access to a WSL setup to try this out there, but just trying this out on a different Ubuntu, it installs fine. That file definitely exists to be downloaded. It's hard to know what might be the cause without more information.

Just going off the output, it looks like it failed here: https://github.com/asdf-community/asdf-hashicorp/blob/master/bin/install#L84 so if you can try that curl manually, maybe you'll see what error `curl` is returning?

**Comment by rsc3600** [comment]
Hey @DustinChaloupka,

Thanks  for responding, I appreciate it. This seems to be a local DNS issue for me- I haven't resolved it yet but it seems like it's not a universal bug
